In [31]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import OneHotEncoder
from sklearn import set_config
from sklearn.preprocessing import MinMaxScaler
set_config(display='diagram')

In [7]:
X = pd.DataFrame(
    {'city': ['London', 'London', 'Paris', 'Sallisaw'],
     'title': ["His Last Bow", "How Watson Learned the Trick",
               "A Moveable Feast", "The Grapes of Wrath"],
     'expert_rating': [5, 3, 4, 5],
     'user_rating': [4, 5, 4, 3]})

In [8]:
X

city                         title  expert_rating  user_rating
0    London                  His Last Bow              5            4
1    London  How Watson Learned the Trick              3            5
2     Paris              A Moveable Feast              4            4
3  Sallisaw           The Grapes of Wrath              5            3

In [9]:
column_tran = ColumnTransformer([
    ('categories',  OneHotEncoder(dtype='int'), ['city']),
    ('title_bow', CountVectorizer(), 'title')],
remainder='drop', verbose_feature_names_out=False)
column_tran

ColumnTransformer(transformers=[('categories', OneHotEncoder(dtype='int'),
                                 ['city']),
                                ('title_bow', CountVectorizer(), 'title')],
                  verbose_feature_names_out=False)

In [11]:
column_tran.fit(X)

ColumnTransformer(transformers=[('categories', OneHotEncoder(dtype='int'),
                                 ['city']),
                                ('title_bow', CountVectorizer(), 'title')],
                  verbose_feature_names_out=False)

In [13]:
column_tran.get_feature_names_out()

array(['city_London', 'city_Paris', 'city_Sallisaw', 'bow', 'feast',
       'grapes', 'his', 'how', 'last', 'learned', 'moveable', 'of', 'the',
       'trick', 'watson', 'wrath'], dtype=object)

In [15]:
column_tran.transform(X).toarray()

array([[1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1]])

In [18]:
pd.DataFrame(data=column_tran.transform(X).toarray(),columns=column_tran.get_feature_names_out())

city_London  city_Paris  city_Sallisaw  bow  feast  grapes  his  how  last  \
0            1           0              0    1      0       0    1    0     1   
1            1           0              0    0      0       0    0    1     0   
2            0           1              0    0      1       0    0    0     0   
3            0           0              1    0      0       1    0    0     0   

   learned  moveable  of  the  trick  watson  wrath  
0        0         0   0    0      0       0      0  
1        1         0   0    1      1       1      0  
2        0         1   0    0      0       0      0  
3        0         0   1    1      0       0      1

In [19]:
from sklearn.preprocessing import StandardScaler
from sklearn.compose import make_column_selector

In [24]:
ct = ColumnTransformer([
    ('scale', StandardScaler(), make_column_selector(dtype_include=np.number)),
    ('one_hot', OneHotEncoder(), make_column_selector(pattern='city', dtype_include=object))
])

In [25]:
ct

ColumnTransformer(transformers=[('scale', StandardScaler(),
                                 <sklearn.compose._column_transformer.make_column_selector object at 0x7ff2c0728e10>),
                                ('one_hot', OneHotEncoder(),
                                 <sklearn.compose._column_transformer.make_column_selector object at 0x7ff2c0728c90>)])

In [27]:
ct.fit_transform(X)

array([[ 0.90453403,  0.        ,  1.        ,  0.        ,  0.        ],
       [-1.50755672,  1.41421356,  1.        ,  0.        ,  0.        ],
       [-0.30151134,  0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.90453403, -1.41421356,  0.        ,  0.        ,  1.        ]])

In [28]:
column_trans = ColumnTransformer(
    [('city_category', OneHotEncoder(dtype='int'),['city']),
     ('title_bow', CountVectorizer(), 'title')],
    remainder='passthrough')

In [29]:
column_trans.fit_transform(X)


array([[1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 5, 4],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 3, 5],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 4, 4],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 5, 3]])

In [30]:
column_tran.get_feature_names_out()

array(['city_London', 'city_Paris', 'city_Sallisaw', 'bow', 'feast',
       'grapes', 'his', 'how', 'last', 'learned', 'moveable', 'of', 'the',
       'trick', 'watson', 'wrath'], dtype=object)

In [33]:
column_trans = ColumnTransformer(
    [('city_category', OneHotEncoder(), ['city']),
     ('title_bow', CountVectorizer(), 'title')],
    remainder=MinMaxScaler())
column_trans

ColumnTransformer(remainder=MinMaxScaler(),
                  transformers=[('city_category', OneHotEncoder(), ['city']),
                                ('title_bow', CountVectorizer(), 'title')])

In [35]:
from sklearn.compose import make_column_transformer
column_trans = make_column_transformer(
    (OneHotEncoder(), ['city']),
    (CountVectorizer(), 'title'),
    remainder=MinMaxScaler())
column_trans

ColumnTransformer(remainder=MinMaxScaler(),
                  transformers=[('onehotencoder', OneHotEncoder(), ['city']),
                                ('countvectorizer', CountVectorizer(),
                                 'title')])

In [36]:
ct = ColumnTransformer(
         [("scale", StandardScaler(), ["expert_rating"])]).fit(X)
X_new = pd.DataFrame({"expert_rating": [5, 6, 1],
                      "ignored_new_col": [1.2, 0.3, -0.1]})
ct.transform(X_new)

array([[ 0.90453403],
       [ 2.11057941],
       [-3.91964748]])